apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sendbird-webrtc-ios
  description: Public repo used for releasing WebRTC for Calls iOS SDK
  annotations:
    github.com/project-slug: sendbird/sendbird-webrtc-ios
spec:
  type: library
  lifecycle: production
  owner: dep-client-platform
  system: sendbird-calls
